openapi: 3.1.0
info:
  title: Metro AI RPG GitHub Access
  version: 1.0.0
  description: GPT kann über diese API auf dein metro-ai-rpg GitHub-Repo zugreifen.
servers:
  - url: https://api.github.com
    description: GitHub REST API

paths:
  /repos/Panicgrinder/metro-ai-rpg/contents/system/{file}:
    get:
      operationId: getSystemFile
      summary: Lese Datei im /system/-Verzeichnis
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
    put:
      operationId: updateSystemFile
      summary: Schreibe Datei in /system/-Verzeichnis
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                content:
                  type: string
                sha:
                  type: string
      responses:
        '200':
          description: Datei erfolgreich aktualisiert

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas: {}

security:
  - bearerAuth: []
