openapi: 3.1.0
info:
  title: Metro AI RPG – GitHub GPT Access
  description: GPT erhält Lese- und Schreibzugriff auf Steuer-, Daten- und Regeldateien des Rollenspielsystems. Anpassbar über master_index.json.
  version: 1.0.0
servers:
  - url: https://api.github.com
    description: GitHub REST API
paths:

  /repos/Panicgrinder/metro-ai-rpg/contents/master_index.json:
    get:
      operationId: getMasterIndex
      summary: Lese master_index.json
      responses:
        '200':
          description: Datei erfolgreich gelesen
          content:
            application/json:
              schema:
                type: object
    put:
      operationId: updateMasterIndex
      summary: Aktualisiere master_index.json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message, content]
              properties:
                message:
                  type: string
                content:
                  type: string
                sha:
                  type: string
                branch:
                  type: string
      responses:
        '200':
          description: Datei aktualisiert
        '201':
          description: Datei erstellt

  /repos/Panicgrinder/metro-ai-rpg/contents/system/{file}:
    get:
      operationId: getSystemFile
      summary: Lese eine Datei aus dem /system/-Verzeichnis
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
          description: Beispiel: gpt_behavior.json
      responses:
        '200':
          description: Datei erfolgreich gelesen
          content:
            application/json:
              schema:
                type: object
    put:
      operationId: updateSystemFile
      summary: Aktualisiere Datei im /system/-Verzeichnis
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message, content]
              properties:
                message:
                  type: string
                content:
                  type: string
                sha:
                  type: string
                branch:
                  type: string
      responses:
        '200':
          description: Datei aktualisiert
        '201':
          description: Datei erstellt

  /repos/Panicgrinder/metro-ai-rpg/contents/data/{file}:
    get:
      operationId: getDataFile
      summary: Lese eine Datei aus dem /data/-Verzeichnis
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datei erfolgreich gelesen
          content:
            application/json:
              schema:
                type: object
    put:
      operationId: updateDataFile
      summary: Aktualisiere Datei im /data/-Verzeichnis
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message, content]
              properties:
                message:
                  type: string
                content:
                  type: string
                sha:
                  type: string
                branch:
                  type: string
      responses:
        '200':
          description: Datei aktualisiert
        '201':
          description: Datei erstellt

  /repos/Panicgrinder/metro-ai-rpg/contents/RULESET.md:
    get:
      operationId: getRuleset
      summary: Lese das Spielregelwerk
      responses:
        '200':
          description: Datei erfolgreich gelesen
          content:
            application/json:
              schema:
                type: object

  /repos/Panicgrinder/metro-ai-rpg/contents/README.md:
    get:
      operationId: getReadme
      summary: Lese die Projektbeschreibung
      responses:
        '200':
          description: Datei erfolgreich gelesen
          content:
            application/json:
              schema:
                type: object

  /repos/Panicgrinder/metro-ai-rpg/contents/docs/{file}:
    get:
      operationId: getDocsFile
      summary: Lese eine Datei aus dem /docs/-Verzeichnis
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
          description: Beispiel: quickstart.md
      responses:
        '200':
          description: Datei erfolgreich gelesen
          content:
            application/json:
              schema:
                type: object

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []